services:
  foundry:
    image: cooperdramsey/foundryvtt:latest
    hostname: cooperdev-foundry.azurewebsites.net
    init: true
    restart: always
    volumes:
      - fvttbackend:/data
    environment:
      - CONTAINER_PRESERVE_CONFIG=true
      - CONTAINER_VERBOSE=true
