FROM node:alpine

ARG FOUNDRY_RELEASE_URL

ENV ARCHIVE="foundryvtt.zip"

WORKDIR $HOME/foundryvtt

RUN apk add --no-cache wget unzip && \
	wget -O ${ARCHIVE} "${FOUNDRY_RELEASE_URL}" && \
	unzip ${ARCHIVE}
	
VOLUME ["/data"]

EXPOSE 80/TCP
EXPOSE 443/TCP

CMD ["resources/app/main.js", "--port=80", "--headless", "--noupdate",\
  "--dataPath=/data"]