ARG FOUNDRY_RELEASE_URL

FROM node:alpine

RUN
	cd $HOME && \
	mkdir foundryvtt && \
	mkdir foundrydata && \
	cd foundryvtt && \
	wget -O foundryvtt.zip "${FOUNDRY_RELEASE_URL}" && \
	unzip foundryvtt.zip && \
	node resources/app/main.js --dataPath=$HOME/foundrydata
	
VOLUME ["/data"]

EXPOSE 80/TCP
EXPOSE 443/TCP
